

delimiter $$

CREATE TABLE `organization` (
  `ORG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORG_NAME` varchar(50) DEFAULT NULL,
  `DISPLAYNAME` varchar(25) DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `CREATED_EMAILID` varchar(45) DEFAULT NULL,
  `CONTACT_EMAIL` varchar(45) DEFAULT NULL,
  `CONTACT_NO` varchar(20) DEFAULT NULL,
  `WEBSITE` varchar(45) DEFAULT NULL,
  `ADDRESS` varchar(100) DEFAULT NULL,
  `COUNTRY` varchar(25) DEFAULT NULL,
  `TIMEZONE` varchar(10) DEFAULT NULL,
  `SENDER_EMAIL` varchar(45) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `UPDATED_EMAILID` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ORG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8$$

delimiter $$

CREATE TABLE `user` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORG_ID` bigint(20) DEFAULT NULL,
  `EMAIL_ID` varchar(45) DEFAULT NULL,
  `PASSWORD` varchar(50) DEFAULT NULL,
  `DISPLAYNAME` varchar(20) DEFAULT NULL,
  `ROLE` tinyint(4) DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  `CONTACT_NO` varchar(20) DEFAULT NULL,
  `FULL_NAME` varchar(30) DEFAULT NULL,
  `LANGUAGE` varchar(25) DEFAULT NULL,
  `TIMEZONE` varchar(10) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `USER_ORG_ID` (`ORG_ID`),
  CONSTRAINT `USER_ORG_ID` FOREIGN KEY (`ORG_ID`) REFERENCES `organization` (`ORG_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `country_map` (
  `COUNTRY` char(2) NOT NULL,
  `CITY` varchar(50) NOT NULL,
  `REGION` int(11) NOT NULL,
  `X_COORDINATE` int(11) NOT NULL,
  `Y_COORDINATE` int(11) NOT NULL,
  PRIMARY KEY (`COUNTRY`,`CITY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `history` (
  `HISTORY_ID` int(11) NOT NULL,
  `SUBJECT` varchar(50) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `ORG_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`HISTORY_ID`),
  KEY `HISTORY_ORG_ID` (`ORG_ID`),
  CONSTRAINT `HISTORY_ORG_ID` FOREIGN KEY (`ORG_ID`) REFERENCES `organization` (`ORG_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$


delimiter $$

CREATE TABLE `campaign` (
  `CAMPAIGN_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORG_ID` bigint(20) DEFAULT NULL,
  `CAMPAIGN_NAME` varchar(25) DEFAULT NULL,
  `CREATED_EMAILID` varchar(45) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `LAST_MODIFIED_TIME` datetime DEFAULT NULL,
  `ISPOWEREDBY` varchar(20) DEFAULT NULL,
  `SUBJECT` varchar(50) DEFAULT NULL,
  `IMAGE_LOC` varchar(150) DEFAULT NULL,
  `CAMPAIGN_LINK` varchar(50) DEFAULT NULL,
  `UNSUBSCRIBE_LINK` varchar(50) DEFAULT NULL,
  `UNSUBSCRIBE_SUBJECT` varchar(50) DEFAULT NULL,
  `CAMPAIGN_TYPE` tinyint(4) DEFAULT '-1',
  `REPLYTO_MAILID` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`CAMPAIGN_ID`),
  KEY `CAMPAIGN_ORG_ID` (`ORG_ID`),
  CONSTRAINT `CAMPAIGN_ORG_ID` FOREIGN KEY (`ORG_ID`) REFERENCES `organization` (`ORG_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `campaign_sender` (
  `SENDER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORG_ID` bigint(20) DEFAULT NULL,
  `DISPLAY_NAME` varchar(100) DEFAULT NULL,
  `EMAIL_ID` varchar(45) DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`SENDER_ID`),
  KEY `org_campaign_id` (`ORG_ID`),
  CONSTRAINT `org_campaign_id` FOREIGN KEY (`ORG_ID`) REFERENCES `organization` (`ORG_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1$$


delimiter $$

CREATE TABLE `campaign_status` (
  `CAMPAIGN_ID` bigint(20) NOT NULL,
  `ORG_ID` bigint(20) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  `SUBSCRIBER_LIST_ID` bigint(20) DEFAULT NULL,
  `SENDER_ID` bigint(20) DEFAULT NULL,
  `SCHEDULED_ON` datetime DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  `LATEST_SUBSCRIBER_COUNT` bigint(20) DEFAULT NULL,
  `SYNC_STATUS` tinyint(4) DEFAULT NULL,
  `LATEST_UPDATED_SUBSCRIBERID` bigint(20) DEFAULT '0',
  `TOTAL_EVENT_FETCHED` int(11) DEFAULT '0',
  `OPENED` smallint(6) DEFAULT '0',
  `CLICKED` smallint(6) DEFAULT '0',
  `BOUNCED` smallint(6) DEFAULT '0',
  `DROPPED` smallint(6) DEFAULT '0',
  `UNSUBSCRIBED` smallint(6) DEFAULT '0',
  `TOTAL_SUBSCRIBER_SENT` smallint(6) DEFAULT '0',
  `SENT_TIME` datetime DEFAULT NULL,
  `LAST_UPDATED_TIME` datetime DEFAULT NULL,
  `S3_PATH` varchar(300) DEFAULT NULL,
  `CONFIRMATION_MAILID` varchar(45) DEFAULT NULL,
  `TIMEZONE` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`CAMPAIGN_ID`),
  KEY `CAMPAIGN_STATUS_ORG_ID` (`ORG_ID`),
  KEY `CAMPAIGN_STATUS_USER_ID` (`USER_ID`),
  KEY `CAMPAIGN_STATUS_SUB_LIST_ID` (`SUBSCRIBER_LIST_ID`),
  KEY `CAMPAIGN_STATUS_SENDER_ID` (`SENDER_ID`),
  CONSTRAINT `CAMPAIGN_STATUS_CAMPAIGN_ID` FOREIGN KEY (`CAMPAIGN_ID`) REFERENCES `campaign` (`CAMPAIGN_ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `CAMPAIGN_STATUS_ORG_ID` FOREIGN KEY (`ORG_ID`) REFERENCES `organization` (`ORG_ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `CAMPAIGN_STATUS_SENDER_ID` FOREIGN KEY (`SENDER_ID`) REFERENCES `campaign_sender` (`SENDER_ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `CAMPAIGN_STATUS_SUB_LIST_ID` FOREIGN KEY (`SUBSCRIBER_LIST_ID`) REFERENCES `subscriber_list` (`SUBSCRIBER_LIST_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `subscriber_list` (
  `SUBSCRIBER_LIST_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORG_ID` bigint(20) DEFAULT NULL,
  `SUBSCRIBER_LIST_NAME` varchar(25) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `LAST_MODIFIED_TIME` datetime DEFAULT NULL,
  `ACTIVE_COUNT` smallint(6) DEFAULT '0',
  `BOUNCE_COUNT` smallint(6) DEFAULT '0',
  `UNSUBSCRIBER_COUNT` smallint(6) DEFAULT '0',
  PRIMARY KEY (`SUBSCRIBER_LIST_ID`),
  KEY `SUBSCRIBER_LIST_ORG_ID` (`ORG_ID`),
  KEY `SUBSCRIBER_LIST_USER_ID` (`USER_ID`),
  CONSTRAINT `SUBSCRIBER_LIST_ORG_ID` FOREIGN KEY (`ORG_ID`) REFERENCES `organization` (`ORG_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `subscriber_reports` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CAMPAIGN_ID` bigint(20) DEFAULT NULL,
  `SUBSCRIBER_LIST_ID` bigint(20) DEFAULT NULL,
  `EMAIL_ID` varchar(45) DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  `TIME_IN_LONG` bigint(20) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `region` varchar(5) DEFAULT NULL,
  `ip` varchar(15) DEFAULT NULL,
  `country` varchar(2) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SUB_REPORTS_CAMPAIGN_ID` (`CAMPAIGN_ID`,`EMAIL_ID`),
  KEY `SUB_REPORTS_SUB_LIST_ID` (`SUBSCRIBER_LIST_ID`),
  CONSTRAINT `SUB_REPORTS_CAMPAIGN_ID` FOREIGN KEY (`CAMPAIGN_ID`) REFERENCES `campaign` (`CAMPAIGN_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `subscriberid_status` (
  `STATUS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SUBSCRIBER_LIST_ID` bigint(20) DEFAULT NULL,
  `EMAIL_ID` varchar(45) DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`STATUS_ID`),
  KEY `SUB_STATUS_SUB_LIST_EMAIL_ID` (`SUBSCRIBER_LIST_ID`,`EMAIL_ID`),
  KEY `SUB_STATUS_SUB_LIST_ID` (`SUBSCRIBER_LIST_ID`,`STATUS`),
  CONSTRAINT `SUB_STATUS_SUB_LIST_ID` FOREIGN KEY (`SUBSCRIBER_LIST_ID`) REFERENCES `subscriber_list` (`SUBSCRIBER_LIST_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `user_uuid` (
  `user_id` bigint(20) NOT NULL,
  `uuid` varchar(60) NOT NULL,
  `created_time` datetime NOT NULL,
  `type` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `user_id_UNIQUE` (`user_id`),
  KEY `registration_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `usersession` (
  `SESSION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) DEFAULT NULL,
  `ORG_ID` bigint(20) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `EXPIRY_TIME` datetime DEFAULT NULL,
  `IPADDRESS` varchar(15) DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`SESSION_ID`),
  KEY `USERSESSION_USER_ID` (`USER_ID`),
  KEY `USERSESSION_ORG_ID` (`ORG_ID`),
  CONSTRAINT `USERSESSION_ORG_ID` FOREIGN KEY (`ORG_ID`) REFERENCES `organization` (`ORG_ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `USERSESSION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


